CREATE TABLE IF NOT EXISTS USERS (
  ID BIGSERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(255) ,
  EMAIL VARCHAR(255),
  PHONE_NUMBER VARCHAR(255),
  ADDRESS VARCHAR(255),
  BIRTH_DATE DATE
);

CREATE TABLE IF NOT EXISTS CLEANING_TYPE
(
    ID BIGSERIAL PRIMARY KEY,
    KEY VARCHAR(100) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    PRICE DECIMAL NOT NULL
);

INSERT INTO CLEANING_TYPE (KEY, VALUE,PRICE) VALUES ('REGULAR', 'Regular', 100);
INSERT INTO CLEANING_TYPE (KEY, VALUE,PRICE) VALUES ('DEEP', 'Deep cleaning', 240);
INSERT INTO CLEANING_TYPE (KEY, VALUE,PRICE) VALUES ('POST_RENOVATION', 'Post-renovation', 500);
INSERT INTO CLEANING_TYPE (KEY, VALUE,PRICE) VALUES ('ECO_CLEANING', 'Eco cleaning', 160);


CREATE TABLE IF NOT EXISTS ADDITIONAL_SERVICE(
    ID BIGSERIAL PRIMARY KEY,
    KEY VARCHAR(100) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    ESTIMATED_TIME_HOURS DECIMAL NOT NULL,
    PRICE DECIMAL NOT NULL
);

INSERT INTO ADDITIONAL_SERVICE (KEY, VALUE, ESTIMATED_TIME_HOURS, PRICE) VALUES ('FRIDGE_CLEANING', 'Fridge cleaning', 0.5, 30);
INSERT INTO ADDITIONAL_SERVICE (KEY, VALUE, ESTIMATED_TIME_HOURS, PRICE) VALUES ('VACUUM_CLEANING', 'Vacuum cleaning', 0, 30);
INSERT INTO ADDITIONAL_SERVICE (KEY, VALUE, ESTIMATED_TIME_HOURS, PRICE) VALUES ('LAUNDRY', 'Laundry', 0, 30);
INSERT INTO ADDITIONAL_SERVICE (KEY, VALUE, ESTIMATED_TIME_HOURS, PRICE) VALUES ('IRONING', 'Ironing', 0.5, 40);
INSERT INTO ADDITIONAL_SERVICE (KEY, VALUE, ESTIMATED_TIME_HOURS, PRICE) VALUES ('CLEANING_SUPPLIES', 'Cleaning supplies', 0, 35);
INSERT INTO ADDITIONAL_SERVICE (KEY, VALUE, ESTIMATED_TIME_HOURS, PRICE) VALUES ('WINDOW_CLEANING', 'Window cleaning (inside)', 1, 60);
INSERT INTO ADDITIONAL_SERVICE (KEY, VALUE, ESTIMATED_TIME_HOURS, PRICE) VALUES ('CABINET_CLEANING', 'Kitchen cabinet cleaning', 1, 60);
INSERT INTO ADDITIONAL_SERVICE (KEY, VALUE, ESTIMATED_TIME_HOURS, PRICE) VALUES ('OVEN_CLEANING', 'Oven cleaning', 0.5, 30);





CREATE TABLE IF NOT EXISTS RESERVATIONS(
    ID BIGSERIAL PRIMARY KEY,
    ADDRESS VARCHAR(255) NOT NULL,
    DATE_TIME TIMESTAMP NOT NULL,
    NUMBER_OF_ROOMS INTEGER NOT NULL,
    NUMBER_OF_BATHROOMS INTEGER NOT NULL,
    COMMENT VARCHAR(255),
    PRICE DECIMAL NOT NULL,
    ESTIMATED_TIME_HOURS DECIMAL NOT NULL,
    KEY_LOCATION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CLEANING_TYPE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (CLEANING_TYPE_ID) REFERENCES CLEANING_TYPE(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS RESERVATION_ADDITIONAL_SERVICE(
    RESERVATION_ID BIGINT NOT NULL,
    ADDITIONAL_SERVICE_ID BIGINT NOT NULL,
    FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(ID),
    FOREIGN KEY (ADDITIONAL_SERVICE_ID) REFERENCES ADDITIONAL_SERVICE(ID),
    PRIMARY KEY (RESERVATION_ID, ADDITIONAL_SERVICE_ID)
);

CREATE INDEX IDX_RESERVATION_USER_ID ON RESERVATIONS(USER_ID);
CREATE INDEX IDX_RESERVATION_CLEANING_TYPE_ID ON RESERVATIONS(CLEANING_TYPE_ID);
CREATE INDEX IDX_RESERVATION_ADDITIONAL_SERVICE_ID ON RESERVATION_ADDITIONAL_SERVICE(ADDITIONAL_SERVICE_ID);
CREATE INDEX IDX_RESERVATION_RESERVATION_ID ON RESERVATION_ADDITIONAL_SERVICE(RESERVATION_ID);
