CREATE TABLE IF NOT EXISTS RATING(
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    rating INT NOT NULL,
    comment VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
)
